# Generated by Django 2.1.7 on 2019-03-07 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190307_1157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
